project:
  type: website
  output-dir: docs

website:
  title: "CEFI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - forecasting-challenges.qmd
      - subscribe.qmd
      - text: Past events 
        menu:
        - summer-school-2023.qmd 
        - ESA-CSEE-symposium-2022.qmd
        - CIEE-working-group-2020.qmd

  page-footer:
    left: "Canadian Ecological Forecasting Initiative" 
    right: 
      - icon: github
        href: https://github.com/CanadianEFI

format:
  html:
    theme: [simplex, custom.scss]
    css: styles.css
    toc: false
    page-layout: full
    grid:
      body-width: 800px
    
