project:
  type: website
  output-dir: docs

website:
  title: "CEFI"
  announcement:
    content: The EFI annual conference is coming to Toronto in 2026. Save the date for August 4-7, 2026 and find more details <a href="https://ecoforecast.org/efi-2026-conference/">here</a>. 
    dismissable: false
    type: info
    position: below-navbar
  navbar:
    left:
      - href: index.qmd
        text: Home
      - forecasting-challenges.qmd
      - text: Past events 
        menu:
        - summer-school-2023.qmd 
        - ESA-CSEE-symposium-2022.qmd
        - CIEE-working-group-2020.qmd
        - CSEE-symposium-2019.qmd
      - text: About us
        menu:
        - steering-committee.qmd
      - href: membership.qmd
        text: Join us
        

  page-footer:
    left: "Canadian Ecological Forecasting Initiative" 
    right: 
      - icon: github
        href: https://github.com/CanadianEFI

format:
  html:
    theme: [simplex, custom.scss]
    css: styles.css
    toc: false
    page-layout: full
    grid:
      body-width: 800px
    
