project:
  type: website
  output-dir: docs

website:
  title: "CEFI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - subscribe.qmd
  page-footer:
    left: "Canadian Ecological Forecasting Initiative" 
    right: 
      - icon: github
        href: https://github.com/CanadianEFI

format:
  html:
    theme: simplex
    css: styles.css
    toc: false
    page-layout: full
    grid:
      body-width: 800px

