---
title: "CSEE 2019 Symposium"
title-block-banner: _assets/banners/csee-symposium-2019.jpg
backgroundcolor: rgb(245, 245, 245)
---

<style>
  .quarto-title-banner {
    height: 400px;
    text-align: center;
    background-position: center;
  }
</style>

<div class=content-center>
<h1 style="font-size: calc(1.5rem + 0.30vw); padding-bottom: 0;">
Prediction in the Anthropocene: Combining theory and practice
</h1>
CSEE annual meeting, 2019 <br>Fredericton, New Brunswick, Canada  
</div>

<div class=content-left>
<br>
Climate change, species invasion, overexploitation, and land-use change continue to intensify pressures on ecosystems worldwide. Increasingly, scientists across disciplines face the challenging task of creating reliable predictions in dynamic and complex natural systems. Reliable forecasting is a key strategy to help mitigate the negative consequences arising from anthropogenic impacts. In this symposium, we bring together researchers working at the interface of science and practice, under the common objective of predicting into an uncertain future. The pairing of theoretical advancements and practical application is essential for making progress under complex and uncertain conditions. While well-informed theory allows us to project into novel situations, collaborative work with practitioners allows us to address priorities and facilitate policy-relevant predictions. In an effort to identify commonalities and differences in theoretical and applied approaches of predicting in the Anthropocene, this symposium encompasses a diverse range of ecosystems (including marine, freshwater, and terrestrial) and various taxa. Additionally, we plan to draw upon research based on diverse techniques, using data from both observational and experimental work. We hope this symposium will lead to a greater exchange of ideas and tools to help further bridge the gap between theoretical and applied science, and to support the continued preservation and management of current and future environments.

</div>

<br>

<div class="content-center">
<p style="font-size: calc(1.25rem + 0.30vw); font-weight: 600;">
Presentations</p>
</div>

<div class="content-left">
<b>Value of information for threatened species management: Predicting where and when we should monitor versus act</b>

Joseph Bennett, Carleton University

<div style="font-size: 0.8rem; font-weight: 300;"> Accurate information on remaining populations of threatened species can be vital for effective management. We can undertake surveys to help find these populations, and we can build models to predict where they may exist. However, the rarer a species becomes, the harder it is to find and model. And gathering information takes time and financial resources that could be used in managing for recovery. How do we know when have we monitored enough that it makes sense to act? Where are the optimal places to monitor, so we can best inform action? Using Canadian case studies, I will present research on value of information theory that can help to solve these problems, and ultimately, better achieve recovery of threatened species. I will also discuss theoretical problems of monitoring for immediate management needs, versus monitoring to improve overall knowledge of a system, and possible strategies to achieve a balance between these approaches.
</div>

<br>

<b>Investigating the effects of microplastics and their associated chemicals to fathead minnows at multiple levels of biological organization</b>

Kennedy Bucci, University of Toronto

<div style="font-size: 0.8rem; font-weight: 300;">Due to the pervasiveness of microplastics (plastic < 5 mm) in aquatic environments, the public, scientists, and decision-makers often ask whether microplastics pose an ecological threat. However, investigation into the effects of microplastics to aquatic organisms is often conducted using simplistic scenarios that do not capture the reality of microplastics as a complex contaminant. These studies generally investigate effects by exposing low trophic-level species to extremely high concentrations of pristine microspheres. The goal of my project is to investigate how environmentally relevant concentrations and types of microplastics affect fathead minnows at multiple levels of biological organization. Fathead minnows were exposed to fragments of virgin polyethylene and polyethylene collected from the shore of Lake Ontario at two concentrations: 100 and 2400 particles per L. The exposure began at the egg stage, 24 hours post-fertilization, and will last until all breeding groups from the control treatment have laid at least 1000 eggs (5-7 months). Throughout this experiment, I will be investigating effects at the suborganismal-level (*e.g.*, histopathology, gene expression), the individual-level (*e.g.*, survival, length, body condition), and the population level (*e.g.*, reproductive success, sex characteristics). I will also be quantifying length, deformities, and epigenetic effects in offspring. Results to date will be presented at this conference.
</div>

<br>

<b>Nitrogen addition enhances terrestrial phosphorous retention</b>

Dr. Ellen Esch, University of Guelph

<div style="font-size: 0.8rem; font-weight: 300;">Nutrient availability influences ecosystem function ranging from biomass production to nutrient retention. In tandem, nitrogen (N) and phosphorus (P) availability may be particularly influential on ecosystem function given widespread prevalence of colimitation dynamics. Within 200 experimental mesocosms, variable amounts of N and P were applied to plant communities consisting of either 1 or 2 functional groups, with leachate collected for 3 months following fertilization. We found (i) that N fertilizer additions reduced P leaching losses, but there was no reciprocal effect of P fertilizer enhancing N retention. Mechanistically, increased plant biomass under N fertilization mediated this effect, pointing towards higher biotic demand for P in the absence of N limitation. (ii) Retention levels were in excess of 95% for N and P across all treatments, and (iii) despite high retention, nutrient runoff was in excess of recommended guidelines for safe drinking water and above levels known to support harmful algal blooms. While our results that adding N can promote P uptake, and hence reduce P leaching, are in line with resource limitation theories, we stress that more research should refine the interactions between N and P availability and leaching at low levels of P addition.
</div>

<br>

<b>Habitat suitability of avian functional groups in current and future land use scenarios in urban environments</b>

Andrew Chin, Toronto and Region Conservation Authority

<div style="font-size: 0.8rem; font-weight: 300;">Consequences of urbanization, such as land use conversion or intensification and natural cover loss, may have both local and regional scales of impact resulting in biodiversity loss and degradation. Therefore, understanding effects of how the current land use changes affect species may help better manage future biodiversity loss. Here we use functional trait groups of species relating to their habitat needs and requirements to assess the status of biodiversity functions in urban environments. Specifically, we focused on two avian functional groups of forest canopy foragers/nesters, and aerial insectivore foragers with data collected from 2007-2017 by the Toronto and Region Conservation Authority, Ontario. We used the amount of land use, vegetation communities, and habitat connectivity as predictors of habitat suitability in the Greater Toronto Area. We used boosted regression trees to model habitat suitability under the current landscape’s capacity to identify where in the landscape support the highest capacity for each functional group. The current landscape’s capacity was compared to the habitat suitability in the future landscape’s capacity based on official plans that will result in land use and cover changes. We found that habitat connectivity mainly influenced habitat suitability and, thus, was an influential factor in current and future scenarios.
</div>

<br>

<b>Factors governing outbreak dynamics in a forest managed for mountain pine beetle</b>

Mélodie Kunegel-Lion, University of Alberta

<div style="font-size: 0.8rem; font-weight: 300;">Mountain pine beetle (MPB) outbreaks have caused major economic losses and ecological damages in North American pine forests. Using ecological and environmental factors impacting MPB life-history and stands susceptibility can help with the detection of MPB infested trees and thereby, improve control. Temperatures, water stress, host characteristics, and beetle pressure are among those ecological and environmental factors. They have different roles on MPB population dynamics at various stages of an outbreak. However, a deeper quantitative analysis on a local scale is required to make detailed connections between ecological and environmental variables and MPB outbreak phases. We studied the current isolated MPB outbreak in Cypress Hills. We used logistic regressions on a highly-detailed and georeferenced data set to determine the factors driving MPB infestations for the different phases of an outbreak. We showed that incoming flights from outside the park are driving MPB population increase during the outbreak onset more than a change in stand susceptibility. At its peak, the MPB outbreak depends mainly on nearby beetle pressure, low summer temperatures, and the presence of tall trees. A decrease in the number of vigorous susceptible pines, as suggested by lower relative humidity levels and a decrease in pine cover, drives the MPB population collapse. This can help managers make appropriate decisions on where to focus their effort depending on which phase the outbreak is in.
</div>

<br>

<b>Modeling scenarios for forest restoration after moose (*Alces alces*) overbrowsing</b>

Meghan Noonan, Memorial University of Newfoundland

<div style="font-size: 0.8rem; font-weight: 300;">Within degraded landscapes, forests are failing to naturally regenerate, resulting in a loss of key species and producing persistent open canopied patches within previously closed canopied systems. Hyper-abundant ungulates can act as a disturbance and hinder natural forest regeneration when they severely overbrowse vegetation. In Newfoundland (Canada), hyper-abundant moose have suppressed balsam fir advanced regeneration producing alternate stable states. We integrated data from field observations and experiments, aerial photographs and drone imagery to parameterize mathematical models of boreal understory and canopy regeneration in Newfoundland. We used simulations to evaluate several restoration scenarios for moose impacted forests, including reduced browsing pressure and seedling planting. Model outcomes suggest active restoration via planting birch and balsam fir seedlings is required to restore the understory and canopy vegetation to its natural state in large canopy gaps, and any planting should be done under low moose browsing pressure or within moose exclosures. In small canopy gaps, passive restoration via moose reduction is sufficient to restore balsam fir, however, birch seedling planting is still required to reach historic birch targets. The study found that Markov models parameterized by aggregate data with simulated herbivory can be used to support experimental studies and strengthen evidence for restoration planning.
</div>

<br>

<b>Projecting the cumulative effects of harvest, fire and roads on forests and boreal caribou: A northwestern Ontario example</b>

Josie Hughes, Environment and Climate Change Canada

<div style="font-size: 0.8rem; font-weight: 300;">An important factor in the decline of boreal woodland caribou is disturbance mediated apparent competition; disturbance improves conditions for predators and alternate prey. We use a spatial stochastic model of forest harvest, fire, succession, and road development to project the cumulative effects of ongoing disturbance in the Churchill range (Northwestern Ontario) of boreal woodland caribou. Succession and harvest parameters are derived from inputs and outputs of existing operational planning models. Without fire or roads our model matches operational plans, and projects an increase in disturbance? from 18% to between 30 and 37% of the landscape within 500m of a cutblock after 40 years. Adding initial roads and fires increases total disturbance to between 59 and 66% after 40 years. Most trunk roads have already been built, so road projections have little impact. A dynamic caribou habitat supply policy and a natural disturbance emulation policy both aggregate harvest. Removing either policy alone has little effect but dispersing small (< 100 ha) cutblocks would increase the total disturbance footprint to between 80 and 85%. Climate change is expected to further increase fire disturbance. Spatial stochastic projections derived from operational planning models allow us to assess the implications of plans for caribou using the language of management.
</div>

<br>

<b>Predicting caribou resource selection and demography under landscape and climate change</b>

Frances Stewart, Natural Resources Canada

<div style="font-size: 0.8rem; font-weight: 300;">Climate change, species invasion, overexploitation, and land-use change continue to intensify pressures on ecosystems worldwide. Increasingly, scientists across disciplines face the challenging task of creating reliable predictions in dynamic and complex natural systems. Reliable forecasting is a key strategy to help mitigate the negative consequences arising from anthropogenic impacts. In this symposium, we bring together researchers working at the interface of science and practice, under the common objective of predicting into an uncertain future. The pairing of theoretical advancements and practical application is essential for making progress under complex and uncertain conditions. While well-informed theory allows us to project into novel situations, collaborative work with practitioners allows us to address priorities and facilitate policy-relevant predictions. In an effort to identify commonalities and differences in theoretical and applied approaches of predicting in the Anthropocene, this symposium encompasses a diverse range of ecosystems (including marine, freshwater, and terrestrial) and various taxa. Additionally, we plan to draw upon research based on diverse techniques, using data from both observational and experimental work. We hope this symposium will lead to a greater exchange of ideas and tools to help further bridge the gap between theoretical and applied science, and to support the continued preservation and management of current and future environments.
</div>

<br>

<b>Consequences of linked genomic architectures for population responses to environmental change</b>

Rebekah Oomen, University of Oslo

<div style="font-size: 0.8rem; font-weight: 300;">Recent advances in both next-generation sequencing technologies and eco-evolutionary modelling are unlocking the potential for integrating genomic information into predictions of population responses to environmental change. One key aspect in this regard is genomic architecture: the structural characteristics and associated inheritance models of genes underlying adaptive traits. For example, whether a trait is controlled primarily by a single locus or multiple loci will greatly influence its evolution in response to environmental stressors. As single-locus control of complex traits is thought to be rare, eco-evolutionary models typically assume many unlinked loci are involved in adaptation. Yet, blocks of physically linked genes that undergo little or no recombination, such as those associated with some chromosomal rearrangements, have emerged as taxonomically widespread phenomena that can facilitate rapid adaptation, especially in the face of gene
flow. Inheritance of linked genomic architectures resembles that of single loci, thus enabling single-locus-like modeling of polygenic adaptation. We develop single-locus evolutionary theory for adaptive traits largely controlled by multiple linked loci for the purpose of predicting responses of natural populations to directional environmental stressors, such as climate change and harvesting. We review known systems for which such an approach might be useful and discuss barriers to implementation.
</div>

<br>

</div>

<br>
<br>

<div class=photo-reference>
Thanks <a href="https://flic.kr/p/HPnLX2" target="_blank">Jared Rover</a> for the beautiful photo displayed on this page ☺ 
</div>