---
title: "ESA & CSEE 2022 Symposium"
title-block-banner: _assets/banners/esa-csee-symposium.jpg
backgroundcolor: rgb(245, 245, 245)
---

<style>
  .quarto-title-banner {
    height: 400px;
    text-align: center;
    background-position: center;
  }
</style>

<div class=content-center>
<h1 style="font-size: calc(1.5rem + 0.30vw); padding-bottom: 0;">
A comparative perspective on<br>integrating ecological forecasting with decision-making
</h1>
Joint annual meeting for ESA & CSEE, 2022<br>
Montreal, Québec, Canada
</div>

<div class=content-left>
<br>
As the rate of human impact accelerates, <i>A Change Is Gonna Come</i> for social and ecological systems, requiring more rapid and science-based decision-making. Ecological forecasting — the process of predicting changes in ecological systems and their components with specified uncertainties — is useful to assist decision-makers in responding to environmental and societal concerns, even in uncertain conditions. Today, the recent availability of cyberinfrastructure, open-source data and novel techniques have increased opportunities to generate ecological forecasts. However, to design forecasts that are useful for decision-making, forecasts must not only be reliable but also must account for the interests and needs of decision-makers and those affected by the decision-making process. The challenge of accommodating those needs and interests is formidable as even when best practices for integrating forecasts into decision-making are known, mismatches can still occur between idealized practices and those adopted to build forecasting models. Both the development of strategies to tackle the divide between forecasting and decision-making and the challenges of their implementation need to be addressed across different sectors and levels of government.

In this session, we began by outlining some of the best practices for bridging the divide between ecological forecasting and decision-making. These proposed best practices were generated by academic, government and industry researchers who have experience building forecasts and/or working with decision-makers. The first talk outlining these practices served as a foundation for the session. Each following speaker focused on a different case study where forecasts were either successfully or unsuccessfully adopted in a decision-making context, and discuss why this outcome occurred. Speakers highlighted practices they perceived to be most beneficial, from using more advanced techniques and quantifying uncertainties, to improving communication and involving decision-makers earlier in the forecasting process, and how successful they were at implementing these practices. As this topic spans across different fields, the speakers in this organized oral session discussed creating forecasts to address a range of issues, from caribou conservation to pandemic planning. Overall, the session highlighted areas of forecasting where we have better succeeded as a scientific community and where we still must work to close the gap between the idealized version of ecological forecasting and the reality of forecasting for decision making.
</div>
<br>

<div class="content-center">
<p style="font-size: calc(1.25rem + 0.30vw); font-weight: 600;">
Presentations</p>
</div>

<div class="content-left">
<b>Guidelines for bridging the divide between ecological forecasts and decision-making</b>

Korryn Bodner*, Carina Rauen Firkowski, Joseph Bennett, Cole Brookson, Michael Dietze, Stephanie Green, Josie Hughes, Jeremy Kerr, Mélodie Kunegel-Lion, Shawn Leroux, Eliot McIntire, Péter Molnár, Craig Simpkins, E. W. Tekwa, Alexander Watts & Marie-Josée Fortin

<div style="font-size: 0.8rem; font-weight: 300;">As the world continues to experience rapid human-induced changes, decision-makers are often pressured to respond to environmental and social challenges in uncertain circumstances. Forecasting models are important analytical tools that can help decision-makers prepare for these challenges and will be increasingly used to address a range of issues from species conservation to resource management to disease outbreaks. Here, we outline general best practices for creating forecasts in decision-making contexts. These best practices were developed through a working group and are based on the experiences of researchers working in academia, government, and industry.

Our best practices encompass strategies for better model development at the science-policy interface. They range from specific technical practices such as quantifying uncertainties, building adaptable models, and creating reusable code, to soft skill practices such as building diverse teams, developing communication techniques, and addressing biases for different audiences. We also categorize strategies based on the time and resources required to implement them, providing first and next steps for researchers desiring to begin or further invest in forecasting. Lastly, we highlight some of the main external obstacles that can prevent good forecasting practices from being adopted in reality. This talk serves as the foundation for this oral session and will provide the benchmarks to evaluate where the forecasting community has most succeeded in integrating forecasting and decision-making, and where future effort should be focused.
</div>

<br>

<b>Forecasting cumulative effects of anticipated resource development on wildlife and vegetation in the James Bay Lowlands of northern Ontario, Canada</b>

Josie Hughes*, Frances Stewart, Jennifer Baltzer, Lisa Venier, Stephanie Avery-Gomm, Raquel Alfaro-Sánchez, Alex Chubaty, Steven Cumming, Sarah Endicott, Leonardo Frid, Cheryl Johnson, Samantha McFarlane, Eliot McIntire & Philip Wiebe

<div style="font-size: 0.8rem; font-weight: 300;">The James Bay Lowlands in Northern Ontario, Canada, falls within one of the largest areas of intact wetlands on the planet, containing one of the largest soil carbon stores. The region is home to Indigenous peoples and wildlife, including the threatened boreal woodland caribou. It is presently inaccessible by road. There is an urgent need to assess the potential environmental impacts of proposed mining of ‘Ring of Fire' mineral deposits. Challenges for forecasting regional cumulative impacts of mining development and ongoing climate warming on vegetation and caribou include: lack of baseline information on the distribution and dynamics of vegetation, natural disturbance regimes, and the distribution, status, and behaviour of wildlife; the cost and logistical difficulty of data collection in remote areas; a lack of ethical space for engagement among scientists and Indigenous communities; and lack of quantitative models of peatland vegetation dynamics. 

We used available models of vegetation dynamics and caribou responses to explore a framework for integrating models into a decision support tool. We use this tool to highlight the needs and possibilities for impact assessment in the region, to identify opportunities for baseline data collection, to begin building partnerships, and to demonstrate the potential for open, modular decision support tools to better integrate ecological knowledge into decision making.
</div>

<br>

<b>Forecasting Pacific salmon recruitment using empirical dynamic modeling</b>

Luke Rogers*, Andrew Edwards & Carrie Holt

<div style="font-size: 0.8rem; font-weight: 300;">Attractor reconstruction offers a tantalizing suite of methods to forecast wildlife abundance. Empirical dynamic modeling (EDM) and the closely related multiview embedding (MVE) match recent abundance patterns with similar patterns in the past to forecast abundance in the future. This allows forecasting to proceed without structural assumptions about the relationship between response and explanatory variables. Further, these methods offer a natural way to include environmental covariates among the explanatory variables. Including environmental covariates in single-species assessments and forecasting is a major focus of the ecosystem approach to fisheries management (EAFM), a stepping stone to multi-species ecosystem-based management (EBM). However, empirical dynamic modeling and related methods are often data-intensive, opaque to users, and deployed in unrealistic forecast settings. We ask, do empirical dynamic modeling and multiview embedding outperform conventional model-based methods to forecast sockeye salmon recruitment abundance in the Fraser River? We used 65 years of spawner abundance and four environmental covariates to forecast 20 years of recruitment abundance in 10 sockeye salmon stocks. We developed an R package where the code for these methods is visible to the public. We forecast recruitment each year using only previous data, mimicking real-world forecasting scenarios, and compared forecasts using accepted forecast metrics.
</div>

<br>

<b>Tales from the trenches: Modelling and pandemic preparedness and response in Canada</b>

Amy Greer*

<div style="font-size: 0.8rem; font-weight: 300;">As we emerge from the SARS-CoV-2 pandemic commissions will be convened to dissect the decisions that were made by organizations, and governments. Decision-makers have both the opportunity and responsibility to meet the critical challenges of public health emergencies. Past inquiries, including the one conducted following SARS-CoV-1 have drawn attention to the need for robust critical thinking and the use of the precautionary principle during times of crisis.

Behavioural economics has demonstrated that all decision-makers are influenced by their beliefs, biases, and other constraints when making choices. Yet, our primary response has been to call for improved transparency around decision-making. I would argue that transparency alone is not enough. We need to embrace more structured approaches that can be used to better engineer the decision-making environment when communicating modelling results to decision-makers and knowledge users. The role of infectious disease modelling in Canadian pandemic preparedness and response activities in 2003 (SARS-CoV-1), 2009 (pandemic influenza A, H1N1), and 2022 (SARS-CoV-2) represents a unique case study with which to consider how forecasts inform decision-making with a specific focus on successes and failures.

As we head into the post-mortem pandemic period, reviews of our pandemic modelling and response across all sectors will clearly demonstrate that we must better support and structure decision-making environments that mitigate the impact of cognitive bias. We must consider the possibility that employing a more structured framework for decision environments would improve processes and policy decisions. Public health relies heavily on risk communication within organizations and between leaders and the public. The integration of the best available empirical evidence from epidemiology, public health, mathematics, and statistics combined with psychology and behavioural economics can support the creation of an institutional culture of transparency around decision-making that will better enable models to guide policy change.
</div>

<br>

<b>Trait‐based vulnerability reveals hotspots of potential impact for a global marine invader</b>

Stephanie Green*, Cole Brookson & Christi Linardich

<div style="font-size: 0.8rem; font-weight: 300;">Mitigating and anticipated ecological and economic impacts of biological invasion before they occur requires knowledge products that identify the types of effects most likely to manifest and where these effects might be most intense. Predation from the invasive Indo-Pacific lionfish is likely to amplify declines in marine fishes observed in multiple ocean basins. As the invasion intensifies and expands, there is an urgent need to identify species that are most at risk for extirpation—and possible extinction—from this added threat. To address this gap and inform conservation plans, we develop and apply a quantitative framework for classifying the relative vulnerability of fishes based on morphological and behavioural traits known to influence susceptibility to lionfish predation (e.g. body shape, water column position and aggregation behaviour), habitat overlap with lionfish, and degree of geographic range restriction. We use this framework to forecast the vulnerability of fish communities across the invaded range and head of the invasion front.

Applying the framework to fishes across the invaded Caribbean Sea and ahead of the invasion front in the southwestern Atlantic revealed the identity of at least 77 fishes with relatively small ranges that are likely to be most affected by lionfish predation. Trait-based vulnerability scores significantly predict the probability of fishes appearing within the diets of lionfish across the invaded region. Spatial richness analyses reveal hotspots of vulnerable species in the Bahamas, Belize and Curaçao. Crucially, our framework identifies 29 vulnerable fishes endemic to Brazil, which has not yet been colonized by lionfish. Of these, we suggest reefs around offshore island groups occupied by a dozen highly vulnerable and range-restricted species as priorities for intervention should lionfish spread to the region. Observations of the rate of lionfish spread across the invaded range suggest that an average of 5 years (with a median of nearly 2 years) elapses from first sighting to maximum observed densities. This lag may allow managers to mobilize plans to suppress lionfish ahead of an invasion front in priority locations. Our framework also provides a method for assessing the relative vulnerability of cryptobenthic and/or deep-reef fishes, for which population-monitoring data are limited.
</div>

<br>

<b>Contributing to caribou land management plans in northern ecosystems while data, models, objectives and the ecosystems are in flux</b>

Eliot McIntire*, Tati Micheletti, Ceres Barros, Frances Stewart, Ian Eddy, Celine Boisvenue, Junior Tremblay, Mathieu Leblond, Alex Chubaty, Steven Cumming, Alana Westwood, Trevor Teed, James Hodson & Samuel Hache

<div style="font-size: 0.8rem; font-weight: 300;">Applied ecological sciences face two major, accelerating challenges: a world with rapid socio-ecological changes and an influx of data and models. Under these conditions, developing ecological forecasts that are sufficiently reliable, responsive and flexible to the needs of rights holders, policy makers, land managers, stakeholders and the public is extremely difficult. It is necessary to develop an ecological forecasting approach that can keep pace with changes to all these variables. Recently, McIntire et al (Ecology Letters, 2022) introduced the PERFICT approach, a clear framework based on nimble yet robust workflows linking management objectives, data, ecological models and results.

To demonstrate this approach, we present the Western Boreal Initiative as a case study. This multi-year ecological forecasting project initially located in the territory of the Dene Nation and other First Peoples (also known as the Northwest Territories, Canada) includes co-production of knowledge between Indigenous and non-Indigenous researchers to support woodland caribou recovery planning. Over the first 2 years of the project, the project objectives, the datasets and the models have frequently been updated or changed; many more such changes are anticipated, exemplifying the need for the PERFICT approach.

Despite forecasts of increased rates of disturbance under climate change, our modelling suggests that caribou populations in the Northwest Territories’ boreal forests could remain stable, in spite of notable changes to habitat. Although several dimensions of this complex issue have not yet been fully woven into our results, our approach allows us to integrate these changes to help bring the most up-to-date data to decisions while enabling the active involvement of all partners. By sharing this approach, we demonstrate some challenges and possible solutions for an applied ecological problem that can be nimble enough for a world under constant flux.
</div>

<br>

(*) Presenting authors
</div>

<br>
<br>

<div class=photo-reference>
Thanks <a href="https://www.pexels.com/photo/rocks-in-the-athabasca-river-5833890/" target="_blank">James Wheeler</a> for the beautiful photo displayed on this page ☺
</div>